repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.8.0
  hooks:
  - id: isort
    args:
    - --multi-line=3
    - --trailing-comma
    - --force-grid-wrap=0
    - --combine-as
    - --line-width=88

- repo: https://github.com/ambv/black
  rev: 21.5b0
  hooks:
  - id: black
    language_version: python3.7

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
  - id: mypy

- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.9.1
  hooks:
  - id: flake8
    args:
    - --max-line-length=80
    - --select=C,E,F,W,B,B950
    - --ignore=E501,W503,E203
